name: release github pages

on:
  push:
    branches:
      - master
    
jobs:
  release:
    runs-on: ubuntu-latest  
    steps:
    - name: publish helm
      uses: helm/chart-releaser-action@v1.4.0
      with:
        charts_dir: helm
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
